### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by cameronwilby** [knorthfield/pietimer#11]
In Chrome Version 30.0.1599.69 m, the following two errors are shown in the console, and there is no pie on the screen :(

First
--
Refused to execute script from 'https://github.com/knorthfield/pietimer/raw/master/jquery.pietimer.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. pietimer:1

Second
--
Uncaught TypeError: Object [object Object] has no method 'pietimer'

**Comment by j-ulrich** [comment]
I think there was a misunderstanding: I think @cameronwilby was talking about the demo on your website, i.e. http://www.northfieldx.co.uk/pietimer/
Because it's not working due to direct linking to https://github.com/knorthfield/pietimer/raw/master/jquery.pietimer.min.js

**Comment by knorthfield** [comment]
Ok, gotcha. Fixed now.
