### ISSUE TITLE
color changing

### ISSUE THREAD

**Issue by ht1080z** [knorthfield/pietimer#17]
Hi, great plugin, very useful for my project.
i am using it with parameters:
      $('#progressTimer').pietimer({
        seconds: 20,
        color: 'rgba(23, 149, 141, 0.8)',
        height: 40,
        width: 40,
        is_reversed: true
      });

Is there any way to make the pie slowly change color when its close to finish?
In the above example the timer is 20sec countdown. I needed to change the color to red when only 5 sec left.
Please advise!

**Comment by knorthfield** [comment]
Hi,
Sorry there's no support in the plugin for that.

Regards,
Kris.

**Comment by knorthfield** [comment]
You could use a CSS animation, that wouldn't be tied to the timing of the JS though so might get a bit weird.

Or you could do something with jQuery UI maybe?
