### ISSUE TITLE
Retina screens?

### ISSUE THREAD

**Issue by qodo** [knorthfield/pietimer#21]
Hi,

This is great thanks very much. One question for you is the use of this on retina screens as it looks a little fuzzy? Is there anything that can be done for these types of display?

Thanks,

**Comment by euangoddard** [comment]
I guess it would be possible to detect the device pixel ratio and multiply the size of the canvas by that amount and then scale it down to fit.

Alternatively switching the rendered to use SVG would fix this issue and the browser support is at least as good

**Comment by qodo** [comment]
Thanks for the reply. Noticed that one of the forks has this updated so planning to use this. Thanks!
